import java.security.SecureRandom
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

// -----------------------------------------------------------------------------
// Custom string-obfuscator task.
//
// Reads a newline-separated catalog of sensitive literals (Frida/Xposed/Magisk
// indicators, /proc paths, sysprop keys, etc.) and emits a generated
// `V.kt` containing:
//   * a per-build random rolling XOR key,
//   * the encoded byte arrays for every catalog entry,
//   * a `s(id)` decode-and-cache function,
//   * stable `const val` integer IDs derived from each entry's text.
//
// Source code refers to entries via `V.s(V.FRIDA)` etc., so `strings(1)` /
// baksmali / naive Frida hooks on `String.equals` cannot trivially see the
// watch list. The XOR key is regenerated on every Gradle build, so each
// release shipped from CI rotates the encoding (`outputs.upToDateWhen { false }`
// forces re-execution).
// -----------------------------------------------------------------------------
abstract class GenerateStringVaultTask : DefaultTask() {
    @get:InputFile
    abstract val catalog: RegularFileProperty

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val className: Property<String>

    @get:OutputDirectory
    abstract val outDir: DirectoryProperty

    @TaskAction
    fun run() {
        val pkg = packageName.get()
        val cls = className.get()
        val entries = catalog.get().asFile.readLines()
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("#") }
            .distinct()
        require(entries.isNotEmpty()) { "obfuscator catalog is empty: ${catalog.get().asFile}" }

        val rng = SecureRandom()
        val key = ByteArray(16).also { rng.nextBytes(it) }

        fun byteToLiteral(b: Byte): String =
            "0x" + String.format("%02X", b.toInt() and 0xFF) + ".toByte()"

        fun deriveId(text: String, taken: MutableSet<String>): String {
            var base = text.uppercase()
                .replace(Regex("[^A-Z0-9]+"), "_")
                .trim('_')
            if (base.isBlank() || base.first().isDigit()) base = "S_$base"
            var unique = base
            var n = 1
            while (!taken.add(unique)) {
                unique = "${base}_$n"
                n += 1
            }
            return unique
        }

        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by GenerateStringVaultTask. DO NOT EDIT.")
        sb.appendLine("// Per-build random XOR key — rotates every build.")
        sb.appendLine("@file:Suppress(\"all\")")
        sb.appendLine("package $pkg")
        sb.appendLine()
        sb.appendLine("internal object $cls {")
        sb.appendLine(
            "    private val K: ByteArray = byteArrayOf(" +
                key.joinToString(", ") { byteToLiteral(it) } + ")"
        )
        sb.appendLine("    private val D: Array<ByteArray> = arrayOf(")
        for (entry in entries) {
            val raw = entry.toByteArray(Charsets.UTF_8)
            val enc = ByteArray(raw.size)
            for (i in raw.indices) {
                enc[i] = (raw[i].toInt() xor key[i % key.size].toInt()).toByte()
            }
            sb.appendLine(
                "        byteArrayOf(" +
                    enc.joinToString(", ") { byteToLiteral(it) } + "),"
            )
        }
        sb.appendLine("    )")
        sb.appendLine()
        sb.appendLine("    private val cache: Array<String?> = arrayOfNulls(D.size)")
        sb.appendLine()
        sb.appendLine("    @JvmStatic fun s(id: Int): String {")
        sb.appendLine("        cache[id]?.let { return it }")
        sb.appendLine("        val e = D[id]")
        sb.appendLine("        val o = ByteArray(e.size)")
        sb.appendLine("        for (i in e.indices) {")
        sb.appendLine("            o[i] = (e[i].toInt() xor K[i % K.size].toInt()).toByte()")
        sb.appendLine("        }")
        sb.appendLine("        val r = String(o, Charsets.UTF_8)")
        sb.appendLine("        cache[id] = r")
        sb.appendLine("        return r")
        sb.appendLine("    }")
        sb.appendLine()
        val taken = mutableSetOf<String>()
        for ((i, entry) in entries.withIndex()) {
            val id = deriveId(entry, taken)
            sb.appendLine("    const val $id: Int = $i")
        }
        sb.appendLine("}")

        val pkgDir = pkg.replace('.', '/')
        val target = outDir.get().asFile.resolve("$pkgDir/$cls.kt")
        target.parentFile.mkdirs()
        target.writeText(sb.toString())
        logger.lifecycle("Generated string vault: ${entries.size} entries -> ${target.relativeTo(project.rootDir)}")
    }
}

val generateStringVault = tasks.register<GenerateStringVaultTask>("generateStringVault") {
    catalog.set(file("src/main/obfuscator/strings.txt"))
    packageName.set("com.dct.securityposture.obf")
    className.set("V")
    outDir.set(layout.buildDirectory.dir("generated/source/obfuscator"))
    // Rotate XOR key on every build.
    outputs.upToDateWhen { false }
}

android {
    namespace = "com.dct.securityposture"
    compileSdk = 35
    ndkVersion = "26.1.10909125"

    sourceSets {
        getByName("main") {
            // Wire the StringVault generator's output directory in as a
            // Kotlin source root. Passing the TaskProvider's flat-mapped
            // output property both adds the directory and registers the
            // task as a dependency of any consumer (compile*Kotlin), so
            // we don't need an explicit `dependsOn`.
            kotlin.srcDir(generateStringVault.flatMap { it.outDir })
        }
    }

    defaultConfig {
        applicationId = "com.dct.securityposture"
        minSdk = 23
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"

        ndk {
            abiFilters += listOf("armeabi-v7a", "arm64-v8a", "x86", "x86_64")
        }

        externalNativeBuild {
            cmake {
                arguments += listOf("-DANDROID_STL=c++_static")
                cppFlags += listOf(
                    "-std=c++17",
                    "-fvisibility=hidden",
                    "-fno-rtti",
                    "-fno-exceptions",
                    "-Os"
                )
            }
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.22.1"
        }
    }

    packaging {
        jniLibs {
            // Keep .so files in the APK so /proc/self/maps reflects them and
            // System.loadLibrary picks them up directly without extracting.
            useLegacyPackaging = false
        }
    }

    buildTypes {
        debug {
            isDebuggable = true
        }
        release {
            isDebuggable = false
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.15.0")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.recyclerview:recyclerview:1.3.2")
    implementation("com.google.android.material:material:1.12.0")
}
